<?php

declare(strict_types=1);

header('X-Robots-Tag: noindex, nofollow, noarchive, nosnippet');
header("Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'");
?>
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex, nofollow, noarchive, nosnippet">
    <title>i18n Manager</title>
    <script>
        (() => {
            const preference = localStorage.getItem('i18n_theme') || 'auto';
            const dark = preference === 'dark' || (preference === 'auto' && window.matchMedia('(prefers-color-scheme: dark)').matches);
            document.documentElement.setAttribute('data-coreui-theme', dark ? 'dark' : 'light');
        })();
    </script>
    <link rel="stylesheet" href="/assets/coreui/css/coreui.min.css">
    <link rel="stylesheet" href="/assets/coreui/css/icons-free.min.css">
    <style>
        :root { --cui-primary: #5856d6; }
        body { background: var(--cui-body-bg); color: var(--cui-body-color); }
        .login-page { min-height: 100vh; display: grid; place-items: center; padding: 1.5rem; background: linear-gradient(135deg, #20233e 0%, #4544a1 55%, #8e8cd8 100%); }
        .login-card { width: min(100%, 430px); border: 0; box-shadow: 0 1.25rem 3rem rgba(20, 20, 50, .3); }
        [data-coreui-theme="dark"] .login-page { background: linear-gradient(135deg, #111522 0%, #28275e 55%, #42406f 100%); }
        .brand-mark { width: 3.25rem; height: 3.25rem; display: inline-grid; place-items: center; border-radius: 1rem; color: #fff; background: linear-gradient(135deg, #6b69e8, #938fff); font-weight: 800; font-size: 1.35rem; }
        .sidebar-brand { font-size: 1.1rem; font-weight: 700; letter-spacing: .01em; }
        .sidebar-brand small { display: block; font-size: .68rem; opacity: .65; font-weight: 400; letter-spacing: .08em; text-transform: uppercase; }
        .app-main { min-width: 0; }
        .view { display: none; }
        .view.active { display: block; }
        .stat-card { min-height: 142px; overflow: hidden; position: relative; }
        .stat-card::after { content: ''; position: absolute; width: 7rem; height: 7rem; border-radius: 50%; right: -2.5rem; top: -2rem; background: rgba(255,255,255,.15); }
        .stat-icon { font-size: 2rem; opacity: .8; }
        .table th { white-space: nowrap; }
        .table td { vertical-align: middle; }
        .translation-value { max-width: 24rem; white-space: normal; word-break: break-word; }
        .drop-zone { border: 2px dashed var(--cui-border-color); border-radius: .75rem; padding: 2.5rem 1rem; text-align: center; background: var(--cui-tertiary-bg); }
        .drop-zone.dragging { border-color: var(--cui-primary); background: rgba(88,86,214,.08); }
        .report-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(155px, 1fr)); gap: .75rem; }
        .report-item { padding: .85rem; border: 1px solid var(--cui-border-color); border-radius: .5rem; background: var(--cui-tertiary-bg); }
        .report-item strong { display: block; font-size: 1.35rem; }
        .modal textarea { min-height: 7rem; }
        .toast-container { z-index: 1080; }
        .theme-select { width: auto; min-width: 8.5rem; }
        @media (min-width: 992px) { .sidebar { position: fixed; inset: 0 auto 0 0; width: 16rem; } .wrapper { margin-left: 16rem; } }
    </style>
</head>
<body>
    <div id="login-screen" class="login-page">
        <div class="card login-card">
            <div class="card-body p-4 p-md-5">
                <div class="text-center mb-4">
                    <div class="brand-mark mb-3">i18n</div>
                    <h1 class="h3 mb-1">Translation Manager</h1>
                    <p class="text-body-secondary mb-0">Centralize suas traduções com segurança.</p>
                </div>
                <div id="login-alert" class="alert alert-danger d-none" role="alert"></div>
                <form id="login-form" novalidate>
                    <div class="mb-3">
                        <label class="form-label" for="login-username">Usuário</label>
                        <input class="form-control form-control-lg" id="login-username" autocomplete="username" required>
                    </div>
                    <div class="mb-4">
                        <label class="form-label" for="login-password">Senha</label>
                        <input type="password" class="form-control form-control-lg" id="login-password" autocomplete="current-password" required>
                    </div>
                    <button class="btn btn-primary btn-lg w-100" id="login-submit" type="submit"><span class="cil-lock-locked me-2"></span>Entrar</button>
                </form>
            </div>
        </div>
    </div>

    <div id="app-shell" class="d-none">
        <aside class="sidebar sidebar-dark bg-dark" id="app-sidebar">
            <div class="sidebar-header border-bottom border-secondary-subtle px-4 py-3">
                <div class="sidebar-brand">i18n Manager<small>Translation service</small></div>
            </div>
            <ul class="sidebar-nav px-2 py-3">
                <li class="nav-title">Workspace</li>
                <li class="nav-item"><a class="nav-link active" href="#dashboard" data-view="dashboard"><span class="nav-icon cil-speedometer"></span>Visão geral</a></li>
                <li class="nav-item"><a class="nav-link" href="#translations" data-view="translations"><span class="nav-icon cil-list"></span>Traduções</a></li>
                <li class="nav-title admin-only">Administração</li>
                <li class="nav-item admin-only"><a class="nav-link" href="#import" data-view="import"><span class="nav-icon cil-cloud-upload"></span>Importar / exportar</a></li>
                <li class="nav-item admin-only"><a class="nav-link" href="#sanitize" data-view="sanitize"><span class="nav-icon cil-filter"></span>Sanitizar banco</a></li>
                <li class="nav-item admin-only"><a class="nav-link" href="#users" data-view="users"><span class="nav-icon cil-people"></span>Usuários</a></li>
                <li class="nav-item admin-only"><a class="nav-link" href="#updater" data-view="updater"><span class="nav-icon cil-cloud-download"></span>Atualizações</a></li>
            </ul>
            <div class="sidebar-footer border-top border-secondary-subtle p-3 mt-auto">
                <div class="small text-white-50 mb-2" id="sidebar-user"></div>
                <button class="btn btn-outline-light btn-sm w-100" id="logout-button"><span class="cil-account-logout me-1"></span>Sair</button>
            </div>
        </aside>

        <div class="wrapper d-flex flex-column min-vh-100">
            <header class="header header-sticky p-0 mb-4 border-bottom bg-body">
                <div class="container-fluid px-4 py-3 d-flex align-items-center justify-content-between">
                    <div class="d-flex align-items-center gap-3">
                        <button class="header-toggler d-lg-none" type="button" id="sidebar-toggler"><span class="cil-menu"></span></button>
                        <div><h1 class="h4 mb-0" id="page-title">Visão geral</h1><small class="text-body-secondary" id="page-subtitle">Acompanhe o estado do catálogo.</small></div>
                    </div>
                    <div class="d-flex align-items-center gap-2"><select class="form-select form-select-sm theme-select" id="theme-select" aria-label="Tema"><option value="auto">Tema do sistema</option><option value="light">Tema claro</option><option value="dark">Tema escuro</option></select><span class="badge text-bg-success" id="role-badge"></span><span class="avatar avatar-md bg-primary text-white" id="user-avatar">?</span></div>
                </div>
            </header>

            <main class="body flex-grow-1 px-3 px-lg-4 pb-5">
                <section class="view active" id="view-dashboard">
                    <div class="row g-3 mb-4">
                        <div class="col-sm-6 col-xl-3"><div class="card text-bg-primary stat-card"><div class="card-body"><div class="d-flex justify-content-between"><div><div class="fs-6 fw-semibold text-white-50">Chaves</div><div class="fs-2 fw-semibold" id="stat-keys">–</div></div><span class="cil-list stat-icon"></span></div><div class="small text-white-50 mt-3">Mensagens de origem</div></div></div></div>
                        <div class="col-sm-6 col-xl-3"><div class="card text-bg-success stat-card"><div class="card-body"><div class="d-flex justify-content-between"><div><div class="fs-6 fw-semibold text-white-50">Traduções</div><div class="fs-2 fw-semibold" id="stat-translations">–</div></div><span class="cil-language stat-icon"></span></div><div class="small text-white-50 mt-3">Valores preenchidos</div></div></div></div>
                        <div class="col-sm-6 col-xl-3"><div class="card text-bg-info stat-card"><div class="card-body"><div class="d-flex justify-content-between"><div><div class="fs-6 fw-semibold text-white-50">Idiomas</div><div class="fs-2 fw-semibold" id="stat-languages">–</div></div><span class="cil-globe-alt stat-icon"></span></div><div class="small text-white-50 mt-3">Códigos em uso</div></div></div></div>
                        <div class="col-sm-6 col-xl-3"><div class="card text-bg-warning stat-card"><div class="card-body"><div class="d-flex justify-content-between"><div><div class="fs-6 fw-semibold text-white-50">Categorias</div><div class="fs-2 fw-semibold" id="stat-categories">–</div></div><span class="cil-folder-open stat-icon"></span></div><div class="small text-white-50 mt-3">Organização do catálogo</div></div></div></div>
                    </div>
                    <div class="row g-4">
                        <div class="col-xl-8"><div class="card h-100"><div class="card-header d-flex justify-content-between align-items-center"><strong>Catálogo de traduções</strong><button class="btn btn-sm btn-primary admin-only" data-action="new-translation"><span class="cil-plus me-1"></span>Nova tradução</button></div><div class="card-body"><p class="text-body-secondary mb-0">Use o menu lateral para consultar, cadastrar, importar ou limpar os dados do catálogo.</p></div></div></div>
                        <div class="col-xl-4"><div class="card border-warning h-100"><div class="card-body"><div class="d-flex align-items-start gap-3"><span class="cil-shield-alt fs-2 text-warning"></span><div><h5>Integridade protegida</h5><p class="text-body-secondary mb-0">O saneamento gera uma cópia de segurança e só aplica mudanças após sua confirmação.</p></div></div></div></div></div>
                    </div>
                </section>

                <section class="view" id="view-translations">
                    <div class="card"><div class="card-body">
                        <div class="d-flex flex-wrap gap-2 justify-content-between align-items-center mb-3"><div><h5 class="card-title mb-1">Traduções</h5><div class="text-body-secondary small" id="translation-count">Carregando…</div></div><div class="d-flex gap-2"><button class="btn btn-outline-secondary" id="export-button"><span class="cil-cloud-download me-1"></span>Exportar CSV</button><button class="btn btn-primary admin-only" data-action="new-translation"><span class="cil-plus me-1"></span>Nova tradução</button></div></div>
                        <div class="row g-2 mb-3"><div class="col-md-3"><label class="visually-hidden" for="filter-category">Categoria</label><select class="form-select" id="filter-category"><option value="">Todas as categorias</option></select></div><div class="col-md-3"><input class="form-control" id="filter-key" placeholder="Buscar chave ou mensagem"></div><div class="col-md-2"><input class="form-control" id="filter-language" placeholder="Idioma"></div><div class="col-md-4"><input class="form-control" id="filter-value" placeholder="Buscar no valor traduzido"></div></div>
                        <div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Categoria</th><th>Mensagem / chave</th><th>Idioma</th><th>Tradução</th><th class="text-end">Ações</th></tr></thead><tbody id="translation-table-body"></tbody></table></div>
                        <div class="d-flex flex-wrap gap-2 justify-content-between align-items-center mt-3"><small class="text-body-secondary" id="pagination-info"></small><div class="btn-group"><button class="btn btn-outline-secondary btn-sm" id="prev-page">Anterior</button><button class="btn btn-outline-secondary btn-sm" id="next-page">Próxima</button></div></div>
                    </div></div>
                </section>

                <section class="view" id="view-import">
                    <div class="row g-4"><div class="col-xl-7"><div class="card"><div class="card-header"><strong>Importar catálogo CSV</strong></div><div class="card-body"><p class="text-body-secondary">Envie um CSV no formato <code>category,message,translation_pt-BR,…</code>. A prévia valida o arquivo antes de qualquer alteração.</p><div class="drop-zone mb-3" id="drop-zone"><span class="cil-cloud-upload fs-1 text-primary d-block mb-2"></span><div class="fw-semibold">Arraste um arquivo CSV aqui</div><div class="small text-body-secondary mb-3">ou selecione no seu computador</div><input class="form-control" type="file" id="csv-file" accept=".csv,text/csv"></div><div class="form-check mb-3"><input class="form-check-input" type="checkbox" id="import-overwrite"><label class="form-check-label" for="import-overwrite">Sobrescrever traduções já existentes</label></div><div class="d-flex gap-2"><button class="btn btn-primary" id="preview-import"><span class="cil-magnifying-glass me-1"></span>Ver prévia</button><button class="btn btn-success d-none" id="run-import"><span class="cil-cloud-upload me-1"></span>Confirmar importação</button></div><div id="import-alert" class="mt-3"></div></div></div></div><div class="col-xl-5"><div class="card"><div class="card-header"><strong>Exportar dados atuais</strong></div><div class="card-body"><p class="text-body-secondary">Baixe um CSV completo e pronto para editar ou versionar junto do projeto.</p><button class="btn btn-outline-primary" id="export-button-secondary"><span class="cil-cloud-download me-1"></span>Baixar CSV atual</button></div></div></div></div>
                    <div class="row g-4 mt-1 admin-only"><div class="col-xl-6"><div class="card border-primary h-100"><div class="card-header"><strong>Backup completo</strong></div><div class="card-body"><p class="text-body-secondary">Baixe um pacote com o banco SQLite, o token e as configurações atuais para levar ao novo servidor.</p><button class="btn btn-primary" id="download-backup"><span class="cil-cloud-download me-1"></span>Baixar backup</button></div></div></div><div class="col-xl-6"><div class="card border-danger h-100"><div class="card-header"><strong>Restaurar backup</strong></div><div class="card-body"><p class="text-body-secondary">A restauração cria um backup de emergência antes de substituir o banco e o ambiente atuais.</p><input class="form-control mb-3" type="file" id="backup-file" accept=".tar.gz,.tgz,application/gzip"><button class="btn btn-danger" id="restore-backup"><span class="cil-history me-1"></span>Restaurar backup</button><div id="restore-alert" class="mt-3"></div></div></div></div></div>
                    <div class="card mt-4 d-none" id="import-preview-card"><div class="card-header"><strong>Resultado da prévia</strong></div><div class="card-body"><div class="report-grid" id="import-report"></div><div id="import-conflicts" class="mt-3"></div></div></div>
                </section>

                <section class="view" id="view-sanitize"><div class="card"><div class="card-header d-flex justify-content-between align-items-center"><div><strong>Saneamento do banco</strong><div class="small text-body-secondary">Normaliza chaves, idiomas, vazios, órfãos e duplicidades.</div></div><button class="btn btn-primary" id="sanitize-preview"><span class="cil-magnifying-glass me-1"></span>Analisar agora</button></div><div class="card-body"><div class="alert alert-warning"><span class="cil-warning me-2"></span>O processo preserva a primeira tradução em caso de conflito, cria backup automático e só grava após confirmação.</div><div id="sanitize-report" class="text-body-secondary">Clique em “Analisar agora” para verificar o banco.</div><div class="d-flex justify-content-end mt-4"><button class="btn btn-danger d-none" id="sanitize-apply"><span class="cil-check me-1"></span>Aplicar saneamento</button></div></div></div></section>

                <section class="view" id="view-users"><div class="card"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><div><h5 class="card-title mb-1">Usuários</h5><div class="small text-body-secondary">Cadastre contas, altere papéis e redefina senhas.</div></div><button class="btn btn-primary" id="new-user"><span class="cil-user-plus me-1"></span>Novo usuário</button></div><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Usuário</th><th>Perfil</th><th>Criado em</th><th class="text-end">Ações</th></tr></thead><tbody id="users-table-body"></tbody></table></div></div></div></section>

                <section class="view" id="view-updater"><div class="row g-4"><div class="col-xl-7"><div class="card"><div class="card-header"><strong>Configuração do updater</strong></div><form id="updater-form"><div class="card-body"><div id="updater-alert"></div><div class="alert alert-warning"><span class="cil-lock-locked me-2"></span>A chave é criptografada antes de ser gravada e nunca é exibida novamente. Use uma chave SSH de deploy sem senha e com acesso somente ao repositório.</div><div class="mb-3"><label class="form-label" for="updater-repository">Repositório Git</label><input class="form-control" id="updater-repository" placeholder="git@github.com:empresa/projeto.git" required maxlength="255"><div class="form-text">SSH é recomendado para usar a chave privada cadastrada.</div></div><div class="mb-3"><label class="form-label" for="updater-branch">Branch</label><input class="form-control" id="updater-branch" value="main" required maxlength="100"></div><div class="mb-3"><label class="form-label" for="updater-private-key">Chave privada SSH</label><textarea class="form-control font-monospace" id="updater-private-key" rows="8" placeholder="-----BEGIN OPENSSH PRIVATE KEY-----"></textarea><div class="form-text" id="updater-key-hint">Obrigatória no primeiro cadastro; em edições, deixe vazia para manter a atual.</div></div></div><div class="card-footer d-flex justify-content-end"><button class="btn btn-primary" type="submit"><span class="cil-save me-1"></span>Salvar configuração</button></div></form></div></div><div class="col-xl-5"><div class="card h-100"><div class="card-header d-flex justify-content-between align-items-center"><strong>Estado da aplicação</strong><button class="btn btn-sm btn-outline-secondary" id="updater-refresh"><span class="cil-reload me-1"></span>Atualizar</button></div><div class="card-body"><div id="updater-status" class="text-body-secondary">Carregando status…</div><div class="d-grid gap-2 mt-4"><button class="btn btn-outline-primary" id="updater-check"><span class="cil-cloud-download me-1"></span>Verificar atualizações</button><button class="btn btn-success" id="updater-apply"><span class="cil-sync me-1"></span>Atualizar aplicação</button></div><div id="updater-action-alert" class="mt-3"></div></div></div></div></div></section>
            </main>
        </div>
    </div>

    <div class="modal fade" id="translation-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><div><h5 class="modal-title" id="translation-modal-title">Nova tradução</h5><small class="text-body-secondary">Preencha uma tradução por vez; a chave pode receber vários idiomas.</small></div><button type="button" class="btn-close" data-coreui-dismiss="modal" aria-label="Fechar"></button></div><form id="translation-form"><div class="modal-body"><div id="translation-alert"></div><div class="row g-3"><div class="col-md-4"><label class="form-label" for="translation-category">Categoria</label><input class="form-control" id="translation-category" required maxlength="255"></div><div class="col-md-8"><label class="form-label" for="translation-message">Mensagem / chave original</label><input class="form-control" id="translation-message" required maxlength="65535"></div><div class="col-md-4"><label class="form-label" for="translation-language">Idioma</label><input class="form-control" id="translation-language" placeholder="pt-BR" required maxlength="35"></div><div class="col-md-8"><label class="form-label" for="translation-value">Tradução</label><textarea class="form-control" id="translation-value" required></textarea></div></div><div class="d-flex gap-2 mt-3"><button type="button" class="btn btn-outline-secondary btn-sm" id="auto-translate"><span class="cil-language me-1"></span>Sugerir com LibreTranslate</button><div class="small text-body-secondary align-self-center" id="translation-alternatives"></div></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-coreui-dismiss="modal">Cancelar</button><button class="btn btn-primary" type="submit" id="save-translation">Salvar tradução</button></div></form></div></div></div>

    <div class="modal fade" id="user-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="user-modal-title">Novo usuário</h5><button type="button" class="btn-close" data-coreui-dismiss="modal" aria-label="Fechar"></button></div><form id="user-form"><div class="modal-body"><div id="user-alert"></div><div class="mb-3"><label class="form-label" for="user-username">Usuário</label><input class="form-control" id="user-username" required maxlength="100" autocomplete="off"></div><div class="mb-3"><label class="form-label" for="user-password">Senha <span class="text-body-secondary fw-normal" id="password-hint"></span></label><input type="password" class="form-control" id="user-password" minlength="8" autocomplete="new-password"></div><div><label class="form-label" for="user-role">Perfil</label><select class="form-select" id="user-role"><option value="user">Usuário (somente leitura)</option><option value="admin">Administrador</option></select></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-coreui-dismiss="modal">Cancelar</button><button class="btn btn-primary" type="submit">Salvar usuário</button></div></form></div></div></div>

    <div class="toast-container position-fixed top-0 end-0 p-3" id="toast-container"></div>
    <script src="/assets/coreui/js/coreui.bundle.min.js"></script>
    <script>
        const state = { token: localStorage.getItem('i18n_token'), role: localStorage.getItem('i18n_role') || 'user', username: localStorage.getItem('i18n_username') || '', translations: [], flat: [], filtered: [], page: 1, perPage: 12, editing: null, editingUser: null, importPreview: null };
        const titles = { dashboard: ['Visão geral', 'Acompanhe o estado do catálogo.'], translations: ['Traduções', 'Consulte, filtre e mantenha seu catálogo.'], import: ['Importar / exportar', 'Troque dados com arquivos CSV.'], sanitize: ['Sanitizar banco', 'Analise e limpe inconsistências com backup.'], users: ['Usuários', 'Gerencie acesso e permissões.'], updater: ['Atualizações', 'Mantenha a aplicação sincronizada com o Git.'] };
        const $ = (id) => document.getElementById(id);
        const modal = (id) => { const Modal = window.coreui?.Modal || window.bootstrap?.Modal; return Modal.getOrCreateInstance($(id)); };
        const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
        function applyTheme(preference) { const selected = ['light', 'dark', 'auto'].includes(preference) ? preference : 'auto'; const dark = selected === 'dark' || (selected === 'auto' && window.matchMedia('(prefers-color-scheme: dark)').matches); document.documentElement.setAttribute('data-coreui-theme', dark ? 'dark' : 'light'); document.documentElement.style.colorScheme = dark ? 'dark' : 'light'; localStorage.setItem('i18n_theme', selected); if ($('theme-select')) $('theme-select').value = selected; }
        const themeMedia = window.matchMedia('(prefers-color-scheme: dark)');
        themeMedia.addEventListener?.('change', () => { if ((localStorage.getItem('i18n_theme') || 'auto') === 'auto') applyTheme('auto'); });
        function toast(message, type = 'success') { const el = document.createElement('div'); el.className = `toast align-items-center text-bg-${type} border-0 show mb-2`; el.setAttribute('role', 'alert'); el.innerHTML = `<div class="d-flex"><div class="toast-body">${escapeHtml(message)}</div><button type="button" class="btn-close btn-close-white me-2 m-auto" data-coreui-dismiss="toast"></button></div>`; $('toast-container').appendChild(el); setTimeout(() => el.remove(), 4200); }
        function showAlert(id, message, type = 'danger') { $(id).innerHTML = message ? `<div class="alert alert-${type} py-2">${escapeHtml(message)}</div>` : ''; }
        function logout() { localStorage.removeItem('i18n_token'); localStorage.removeItem('i18n_role'); localStorage.removeItem('i18n_username'); state.token = null; $('app-shell').classList.add('d-none'); $('login-screen').classList.remove('d-none'); }
        async function api(path, options = {}) { options.headers = { Accept: 'application/json', ...(options.headers || {}), Authorization: `Bearer ${state.token}` }; const response = await fetch(path, options); const type = response.headers.get('content-type') || ''; const data = type.includes('json') ? await response.json() : await response.text(); if (response.status === 401) { logout(); throw new Error('Sessão expirada.'); } if (!response.ok) throw new Error(data?.error || `Erro HTTP ${response.status}`); return data; }
        function setView(name) { if (!titles[name] || (name !== 'dashboard' && name !== 'translations' && state.role !== 'admin')) name = state.role === 'admin' ? 'dashboard' : 'translations'; document.querySelectorAll('.view').forEach((view) => view.classList.toggle('active', view.id === `view-${name}`)); document.querySelectorAll('[data-view]').forEach((link) => link.classList.toggle('active', link.dataset.view === name)); $('page-title').textContent = titles[name][0]; $('page-subtitle').textContent = titles[name][1]; if (name === 'dashboard') loadStats(); if (name === 'translations') loadTranslations(); if (name === 'users') loadUsers(); if (name === 'sanitize') previewSanitize(); if (name === 'updater') loadUpdaterStatus(); history.replaceState(null, '', `#${name}`); }
        function configureRole() { document.querySelectorAll('.admin-only').forEach((el) => el.classList.toggle('d-none', state.role !== 'admin')); $('role-badge').textContent = state.role === 'admin' ? 'Administrador' : 'Somente leitura'; $('sidebar-user').textContent = `${state.username} · ${state.role}`; $('user-avatar').textContent = (state.username[0] || '?').toUpperCase(); }
        function openApp() { $('login-screen').classList.add('d-none'); $('app-shell').classList.remove('d-none'); configureRole(); setView(location.hash.slice(1) || (state.role === 'admin' ? 'dashboard' : 'translations')); }
        async function loadStats() { try { const stats = await api('/api/stats'); $('stat-keys').textContent = stats.keys; $('stat-translations').textContent = stats.translations; $('stat-languages').textContent = stats.languages; $('stat-categories').textContent = stats.categories; } catch (error) { toast(error.message, 'danger'); } }
        async function loadTranslations() { try { state.translations = await api('/api/pull'); state.flat = []; const cats = new Set(); state.translations.forEach((item) => { cats.add(item.category); const entries = Object.entries(item.translations || {}); if (!entries.length) state.flat.push({ category: item.category, message: item.message, lang: '', value: '', source: item }); else entries.forEach(([lang, value]) => state.flat.push({ category: item.category, message: item.message, lang, value, source: item })); }); const select = $('filter-category'); const current = select.value; select.innerHTML = '<option value="">Todas as categorias</option>' + [...cats].sort().map((cat) => `<option value="${escapeHtml(cat)}">${escapeHtml(cat)}</option>`).join(''); select.value = current; applyFilters(); $('translation-count').textContent = `${state.flat.length} registro(s) exibido(s)`; } catch (error) { toast(error.message, 'danger'); } }
        function applyFilters() { const cat = $('filter-category').value; const key = $('filter-key').value.toLowerCase(); const lang = $('filter-language').value.toLowerCase(); const value = $('filter-value').value.toLowerCase(); state.filtered = state.flat.filter((item) => (cat === '' || item.category === cat) && item.message.toLowerCase().includes(key) && item.lang.toLowerCase().includes(lang) && item.value.toLowerCase().includes(value)); state.page = 1; renderTranslations(); }
        function renderTranslations() { const start = (state.page - 1) * state.perPage; const rows = state.filtered.slice(start, start + state.perPage); $('translation-table-body').innerHTML = rows.length ? rows.map((item, index) => { const actualIndex = start + index; return `<tr><td><span class="badge text-bg-light">${escapeHtml(item.category)}</span></td><td class="fw-semibold">${escapeHtml(item.message)}</td><td>${item.lang ? `<span class="badge text-bg-primary">${escapeHtml(item.lang)}</span>` : '<span class="text-body-secondary">–</span>'}</td><td class="translation-value">${item.lang ? escapeHtml(item.value) : '<em class="text-body-secondary">Sem traduções</em>'}</td><td class="text-end text-nowrap">${state.role === 'admin' ? `<button class="btn btn-sm btn-outline-primary me-1" data-edit="${actualIndex}" title="Editar"><span class="cil-pencil"></span></button><button class="btn btn-sm btn-outline-danger" data-delete="${actualIndex}" title="Excluir"><span class="cil-trash"></span></button>` : '<span class="text-body-secondary small">Visualização</span>'}</td></tr>`; }).join('') : '<tr><td colspan="5" class="text-center text-body-secondary py-5">Nenhum registro encontrado.</td></tr>'; const totalPages = Math.max(1, Math.ceil(state.filtered.length / state.perPage)); if (state.page > totalPages) state.page = totalPages; $('pagination-info').textContent = state.filtered.length ? `Mostrando ${start + 1}–${Math.min(start + state.perPage, state.filtered.length)} de ${state.filtered.length}` : 'Nenhum registro'; $('prev-page').disabled = state.page <= 1; $('next-page').disabled = state.page >= totalPages; }
        function resetTranslationForm(item = null) { state.editing = item; $('translation-form').reset(); $('translation-alert').innerHTML = ''; $('translation-alternatives').textContent = ''; $('translation-modal-title').textContent = item ? 'Editar tradução' : 'Nova tradução'; $('save-translation').textContent = item ? 'Sobrescrever tradução' : 'Salvar tradução'; if (item) { $('translation-category').value = item.category; $('translation-message').value = item.message; $('translation-language').value = item.lang; $('translation-value').value = item.value; } }
        function openTranslation(item = null) { resetTranslationForm(item); modal('translation-modal').show(); }
        async function saveTranslation(event) { event.preventDefault(); const category = $('translation-category').value.trim(); const message = $('translation-message').value.trim(); const language = $('translation-language').value.trim().replaceAll('_', '-'); const value = $('translation-value').value.trim(); if (!category || !message || !language || !value) return showAlert('translation-alert', 'Preencha todos os campos.'); const button = $('save-translation'); button.disabled = true; try { await api('/api/push', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ category, message, translations: { [language]: value }, overwrite: Boolean(state.editing) }) }); modal('translation-modal').hide(); toast('Tradução salva.'); await loadTranslations(); loadStats(); } catch (error) { showAlert('translation-alert', error.message); } finally { button.disabled = false; } }
        async function deleteTranslation(item) { if (!confirm(`Excluir ${item.lang ? 'a tradução' : 'a chave'} “${item.message}”?`)) return; try { await api('/api/delete', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ category: item.category, message: item.message, language: item.lang }) }); toast('Registro removido.'); await loadTranslations(); loadStats(); } catch (error) { toast(error.message, 'danger'); } }
        async function autoTranslate() { const message = $('translation-message').value.trim(); const target = $('translation-language').value.trim().split('-')[0].toLowerCase(); if (!message || !target) return showAlert('translation-alert', 'Informe a mensagem e o idioma primeiro.', 'warning'); const button = $('auto-translate'); button.disabled = true; button.innerHTML = '<span class="spinner-border spinner-border-sm me-1"></span>Traduzindo…'; try { const data = await api('/api/translate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ q: message, source: 'auto', target, format: 'text', alternatives: 3 }) }); $('translation-value').value = data.translatedText || ''; $('translation-alternatives').textContent = data.alternatives?.filter((alt) => alt !== data.translatedText).join(' · ') || ''; } catch (error) { showAlert('translation-alert', error.message); } finally { button.disabled = false; button.innerHTML = '<span class="cil-language me-1"></span>Sugerir com LibreTranslate'; } }
        function reportHtml(report) { const labels = { sources_scanned: 'Fontes analisadas', source_normalizations: 'Fontes normalizadas', duplicate_sources: 'Chaves duplicadas', empty_sources: 'Fontes vazias', translations_scanned: 'Traduções analisadas', language_normalizations: 'Idiomas normalizados', duplicate_translations: 'Traduções duplicadas', conflicting_translations: 'Conflitos', empty_translations: 'Traduções vazias', orphan_translations: 'Traduções órfãs', removed_sources: 'Fontes removíveis', removed_translations: 'Traduções removíveis' }; return `<div class="report-grid">${Object.entries(labels).map(([key, label]) => `<div class="report-item"><strong>${escapeHtml(report[key] ?? 0)}</strong><span class="small text-body-secondary">${label}</span></div>`).join('')}</div>`; }
        async function previewSanitize() { if (state.role !== 'admin') return; $('sanitize-apply').classList.add('d-none'); $('sanitize-report').innerHTML = '<div class="text-body-secondary"><span class="spinner-border spinner-border-sm me-2"></span>Analisando…</div>'; try { const data = await api('/api/sanitize/preview'); $('sanitize-report').innerHTML = reportHtml(data.report) + '<p class="small text-body-secondary mt-3 mb-0">A primeira tradução encontrada é preservada quando há conflito.</p>'; const actionable = (data.report.removed_sources || 0) + (data.report.removed_translations || 0) + (data.report.source_normalizations || 0) + (data.report.language_normalizations || 0); if (actionable) $('sanitize-apply').classList.remove('d-none'); } catch (error) { $('sanitize-report').innerHTML = `<div class="alert alert-danger">${escapeHtml(error.message)}</div>`; } }
        async function applySanitize() { if (!confirm('Aplicar o saneamento? Um backup será criado antes da alteração.')) return; const button = $('sanitize-apply'); button.disabled = true; try { const data = await api('/api/sanitize', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ apply: true }) }); $('sanitize-report').innerHTML = reportHtml(data.report) + `<div class="alert alert-success mt-3">Saneamento aplicado. Backup: ${escapeHtml(data.report.backup || 'criado')}</div>`; button.classList.add('d-none'); toast('Banco sanitizado.'); loadStats(); loadTranslations(); } catch (error) { toast(error.message, 'danger'); } finally { button.disabled = false; } }
        function renderImportPreview(preview) { const p = preview; $('import-preview-card').classList.remove('d-none'); $('import-report').innerHTML = [['rows', 'Linhas válidas'], ['new_keys', 'Novas chaves'], ['existing_keys', 'Chaves existentes'], ['translations', 'Traduções'], ['invalid', 'Linhas inválidas']].map(([key, label]) => `<div class="report-item"><strong>${Array.isArray(p[key]) ? p[key].length : escapeHtml(p[key] ?? 0)}</strong><span class="small text-body-secondary">${label}</span></div>`).join(''); $('import-conflicts').innerHTML = p.conflicts?.length ? `<div class="alert alert-warning"><strong>${p.conflicts.length} conflito(s) detectado(s).</strong> Marque “Sobrescrever” para aceitar alterações.</div>` : '<div class="alert alert-success mb-0">Nenhum conflito de tradução detectado.</div>'; $('run-import').classList.toggle('d-none', !p.rows || p.invalid?.length > 0); }
        async function previewImport() { const file = $('csv-file').files[0]; if (!file) return showAlert('import-alert', 'Selecione um arquivo CSV.', 'warning'); const form = new FormData(); form.append('file', file); form.append('preview', '1'); $('preview-import').disabled = true; try { const data = await api('/api/import', { method: 'POST', body: form }); state.importPreview = data.preview; renderImportPreview(data.preview); showAlert('import-alert', 'Prévia concluída. Revise os números antes de importar.', 'success'); } catch (error) { showAlert('import-alert', error.message); } finally { $('preview-import').disabled = false; } }
        async function runImport() { const file = $('csv-file').files[0]; if (!file) return; if (!confirm('Confirmar importação do arquivo?')) return; const form = new FormData(); form.append('file', file); form.append('overwrite', $('import-overwrite').checked ? '1' : '0'); $('run-import').disabled = true; try { const data = await api('/api/import', { method: 'POST', body: form }); toast(`${data.rows} linha(s) importada(s).`); state.importPreview = null; $('import-preview-card').classList.add('d-none'); $('csv-file').value = ''; showAlert('import-alert', 'Importação concluída.', 'success'); loadStats(); loadTranslations(); } catch (error) { showAlert('import-alert', error.message); } finally { $('run-import').disabled = false; } }
        function resetUserForm(user = null) { state.editingUser = user; $('user-form').reset(); $('user-alert').innerHTML = ''; $('user-modal-title').textContent = user ? 'Editar usuário' : 'Novo usuário'; $('password-hint').textContent = user ? '(deixe vazio para manter)' : '(mínimo 8 caracteres)'; if (user) { $('user-username').value = user.username; $('user-role').value = user.role; } }
        async function loadUsers() { try { const users = await api('/api/users'); $('users-table-body').innerHTML = users.map((user) => `<tr><td class="fw-semibold">${escapeHtml(user.username)}${user.username === state.username ? ' <span class="badge text-bg-light">você</span>' : ''}</td><td><span class="badge text-bg-${user.role === 'admin' ? 'primary' : 'secondary'}">${user.role === 'admin' ? 'Administrador' : 'Usuário'}</span></td><td>${escapeHtml(user.created_at || '–')}</td><td class="text-end text-nowrap"><button class="btn btn-sm btn-outline-primary me-1" data-user-edit="${user.id}"><span class="cil-pencil"></span></button><button class="btn btn-sm btn-outline-danger" data-user-delete="${user.id}"><span class="cil-trash"></span></button></td></tr>`).join('') || '<tr><td colspan="4" class="text-center text-body-secondary">Nenhum usuário.</td></tr>'; $('users-table-body').dataset.users = JSON.stringify(users); } catch (error) { toast(error.message, 'danger'); } }
        function renderUpdaterStatus(status) { const stateLabel = status.dirty ? '<span class="badge text-bg-warning">Alterações locais</span>' : '<span class="badge text-bg-success">Árvore limpa</span>'; const keyLabel = status.key_configured ? '<span class="badge text-bg-success">Chave configurada</span>' : '<span class="badge text-bg-danger">Chave ausente</span>'; const sync = status.behind === null ? 'Ainda não verificado' : status.behind === 0 ? 'Aplicação atualizada' : `${status.behind} atualização(ões) disponível(is)`; $('updater-status').innerHTML = `<dl class="row mb-0"><dt class="col-sm-5">Repositório</dt><dd class="col-sm-7 text-break">${escapeHtml(status.repository || 'Não configurado')}</dd><dt class="col-sm-5">Branch atual</dt><dd class="col-sm-7"><code>${escapeHtml(status.branch || '–')}</code></dd><dt class="col-sm-5">Commit</dt><dd class="col-sm-7"><code>${escapeHtml(status.commit || '–')}</code></dd><dt class="col-sm-5">Estado</dt><dd class="col-sm-7">${stateLabel}</dd><dt class="col-sm-5">Credencial</dt><dd class="col-sm-7">${keyLabel}</dd><dt class="col-sm-5">Sincronização</dt><dd class="col-sm-7">${escapeHtml(sync)}</dd></dl>${status.dirty && status.changes ? `<pre class="small bg-body-tertiary p-2 mt-3 mb-0 overflow-auto">${escapeHtml(status.changes)}</pre>` : ''}`; }
        async function loadUpdaterStatus() { try { const data = await api('/api/updater/status'); const status = data.status; renderUpdaterStatus(status); if (!$('updater-repository').value) $('updater-repository').value = status.repository || ''; if (!$('updater-branch').value || $('updater-branch').value === 'main') $('updater-branch').value = status.configured_branch || status.branch || 'main'; $('updater-key-hint').textContent = status.key_configured ? 'Chave configurada. Deixe o campo vazio para mantê-la.' : 'Cadastre uma chave SSH privada para habilitar o updater.'; } catch (error) { $('updater-status').innerHTML = `<div class="alert alert-danger">${escapeHtml(error.message)}</div>`; } }
        async function saveUpdaterConfig(event) { event.preventDefault(); const payload = { repository: $('updater-repository').value.trim(), branch: $('updater-branch').value.trim(), private_key: $('updater-private-key').value.trim() }; try { await api('/api/updater/config', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); $('updater-private-key').value = ''; showAlert('updater-alert', 'Configuração salva com segurança.', 'success'); loadUpdaterStatus(); } catch (error) { showAlert('updater-alert', error.message); } }
        async function checkUpdater() { const button = $('updater-check'); button.disabled = true; $('updater-action-alert').innerHTML = ''; try { const data = await api('/api/updater/check', { method: 'POST' }); renderUpdaterStatus(data.status); toast(data.status.behind ? `${data.status.behind} atualização(ões) encontrada(s).` : 'A aplicação já está atualizada.'); } catch (error) { showAlert('updater-action-alert', error.message); } finally { button.disabled = false; } }
        async function applyUpdater() { if (!confirm('Atualizar a aplicação agora? O updater aceita apenas avanço rápido e não sobrescreve alterações locais.')) return; const button = $('updater-apply'); button.disabled = true; $('updater-action-alert').innerHTML = ''; try { const data = await api('/api/updater/update', { method: 'POST' }); renderUpdaterStatus(data.status); toast(data.status.updated ? 'Aplicação atualizada. Recarregando…' : 'A aplicação já está atualizada.'); if (data.status.updated) setTimeout(() => window.location.reload(), 1800); } catch (error) { showAlert('updater-action-alert', error.message); } finally { button.disabled = false; } }
        async function saveUser(event) { event.preventDefault(); const username = $('user-username').value.trim(); const password = $('user-password').value; const role = $('user-role').value; if (!username || (!state.editingUser && password.length < 8) || (password && password.length < 8)) return showAlert('user-alert', 'Informe um usuário e uma senha com pelo menos 8 caracteres.'); const payload = { username, role }; if (password) payload.password = password; try { await api(state.editingUser ? `/api/users/${state.editingUser.id}` : '/api/users', { method: state.editingUser ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); modal('user-modal').hide(); toast('Usuário salvo.'); loadUsers(); } catch (error) { showAlert('user-alert', error.message); } }
        async function deleteUser(id) { if (!confirm('Excluir este usuário?')) return; try { await api(`/api/users/${id}`, { method: 'DELETE' }); toast('Usuário excluído.'); loadUsers(); } catch (error) { toast(error.message, 'danger'); } }
        async function downloadExport() { try { const response = await fetch('/api/export', { headers: { Authorization: `Bearer ${state.token}` } }); if (!response.ok) { const data = await response.json().catch(() => ({})); throw new Error(data.error || 'Falha ao exportar o catálogo.'); } const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'i18n_messages_app.csv'; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); } catch (error) { toast(error.message, 'danger'); } }
        async function downloadBackup() { try { const response = await fetch('/api/backup', { headers: { Authorization: `Bearer ${state.token}` } }); if (!response.ok) { const data = await response.json().catch(() => ({})); throw new Error(data.error || 'Falha ao criar o backup.'); } const blob = await response.blob(); const disposition = response.headers.get('content-disposition') || ''; const name = disposition.match(/filename="?([^";]+)"?/i)?.[1] || 'i18n-api-backup.tar.gz'; const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = name; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); toast('Backup baixado com sucesso.'); } catch (error) { toast(error.message, 'danger'); } }
        async function restoreBackup() { const file = $('backup-file').files[0]; if (!file) return showAlert('restore-alert', 'Selecione um arquivo de backup.', 'warning'); if (!confirm('Restaurar este backup? O banco atual será salvo automaticamente antes da substituição.')) return; const form = new FormData(); form.append('backup', file); $('restore-backup').disabled = true; try { const data = await api('/api/restore', { method: 'POST', body: form }); showAlert('restore-alert', `Restauração concluída. Backup de emergência: ${data.restore?.emergency_backup || 'criado'}. Faça login novamente.`, 'success'); setTimeout(logout, 1800); } catch (error) { showAlert('restore-alert', error.message); } finally { $('restore-backup').disabled = false; } }
        $('login-form').addEventListener('submit', async (event) => { event.preventDefault(); const button = $('login-submit'); button.disabled = true; showAlert('login-alert', ''); try { const response = await fetch('/api/login', { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify({ username: $('login-username').value.trim(), password: $('login-password').value }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível entrar.'); localStorage.setItem('i18n_token', data.token); localStorage.setItem('i18n_role', data.role || 'user'); localStorage.setItem('i18n_username', data.username || $('login-username').value.trim()); state.token = data.token; state.role = data.role || 'user'; state.username = data.username || ''; openApp(); } catch (error) { showAlert('login-alert', error.message); } finally { button.disabled = false; } });
        $('logout-button').addEventListener('click', logout); $('sidebar-toggler').addEventListener('click', () => $('app-sidebar').classList.toggle('show')); document.querySelectorAll('[data-view]').forEach((link) => link.addEventListener('click', (event) => { event.preventDefault(); setView(link.dataset.view); $('app-sidebar').classList.remove('show'); })); document.querySelectorAll('[data-action="new-translation"]').forEach((button) => button.addEventListener('click', () => openTranslation())); $('translation-form').addEventListener('submit', saveTranslation); $('auto-translate').addEventListener('click', autoTranslate); $('translation-table-body').addEventListener('click', (event) => { const edit = event.target.closest('[data-edit]'); const del = event.target.closest('[data-delete]'); if (edit) openTranslation(state.filtered[Number(edit.dataset.edit)]); if (del) deleteTranslation(state.filtered[Number(del.dataset.delete)]); }); ['filter-category', 'filter-key', 'filter-language', 'filter-value'].forEach((id) => $(id).addEventListener(id === 'filter-category' ? 'change' : 'input', applyFilters)); $('prev-page').addEventListener('click', () => { if (state.page > 1) { state.page--; renderTranslations(); } }); $('next-page').addEventListener('click', () => { if (state.page < Math.ceil(state.filtered.length / state.perPage)) { state.page++; renderTranslations(); } }); $('export-button').addEventListener('click', downloadExport); $('export-button-secondary').addEventListener('click', downloadExport); $('download-backup').addEventListener('click', downloadBackup); $('restore-backup').addEventListener('click', restoreBackup); $('preview-import').addEventListener('click', previewImport); $('run-import').addEventListener('click', runImport); $('sanitize-preview').addEventListener('click', previewSanitize); $('sanitize-apply').addEventListener('click', applySanitize); $('new-user').addEventListener('click', () => { resetUserForm(); modal('user-modal').show(); }); $('user-form').addEventListener('submit', saveUser); $('users-table-body').addEventListener('click', (event) => { const users = JSON.parse($('users-table-body').dataset.users || '[]'); const edit = event.target.closest('[data-user-edit]'); const del = event.target.closest('[data-user-delete]'); if (edit) { resetUserForm(users.find((user) => Number(user.id) === Number(edit.dataset.userEdit))); modal('user-modal').show(); } if (del) deleteUser(Number(del.dataset.userDelete)); });
        $('theme-select').addEventListener('change', (event) => applyTheme(event.target.value)); $('updater-form').addEventListener('submit', saveUpdaterConfig); $('updater-refresh').addEventListener('click', loadUpdaterStatus); $('updater-check').addEventListener('click', checkUpdater); $('updater-apply').addEventListener('click', applyUpdater);
        applyTheme(localStorage.getItem('i18n_theme') || 'auto');
        if (state.token) openApp();
    </script>
</body>
</html>
